# Development profile using in-memory H2 database
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/zero;MODE=PostgreSQL;AUTO_SERVER=TRUE;
    username: sa
    password: 11
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
